name: diff
description: diff
inputs:
  subdir:
    required: true
outputs:
  diff-env:
    value: ${{ steps.diff.outputs.diff-env }}
  diff-dir:
    value: ${{ steps.diff.outputs.diff-dir }}
  diff-count:
    value: ${{ steps.diff.outputs.diff-count }}
runs:
  using: composite
  steps:
    - id: diff
      env:
        TARGET_BRANCH: ${{ github.base_ref }}
      run: |
        git fetch origin ${TARGET_BRANCH}
        master_diff=`git diff origin/${TARGET_BRANCH} HEAD --name-only --relative=${{ inputs.subdir }}`
        count=`echo ${master_diff} | wc -l`
      shell: bash
