name: lint

permissions:
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
    types:
      - opened
      - synchronize

env:
  TF_VERSION: "1.5.0"

jobs:
  dir-identify:
    outputs:
      target_dir: ${{ steps.changes.outputs.target_dir }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - name: github-action misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
      - uses: dorny/paths-filter@v3
        name: check-dir
        id: dir-filter
        with:
          list-files: json
          filters: |
            changed: 'terraform*/**'
      - name: detect-target-dir
        id: changes
        env:
          changed: ${{steps.dir-filter.outputs.changed_files}}
        run: |
          target_dir="$( echo ${changed} | jq -r '.[]' | xargs dirname | sort | uniq | jq -s -R -c 'split("\n") | map(select(. != ""))')"
          echo "target_dir=${target_dir}" >> $GITHUB_OUTPUT
        shell: bash

  tflint:
    needs: dir-identify
    if: needs.dir-identify.outputs.target_dir != '[]'
    strategy:
      matrix:
        target_dir: ${{ fromJSON(needs.dir-identify.outputs.target_dir) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - run: echo "Building ${{ matrix.target_dir }}"

      - name: Cache plugin dir
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${env.TF_VERSION}

      - name: Terraform fmt
        id: terraform-fmt
        working_directory: ${{ matrix.target_dir }}
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: terraform-init
        working_directory: ${{ matrix.target_dir }}
        run: terraform init

      - name: Terraform Validate
        id: terraform-validate
        working_directory: ${{ matrix.target_dir }}
        run: terraform validate -no-color

      - name: tflint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.github_token }}
          tflint_config: "${{ github.workspace }}/.tflint.hcl"
          working_directory: ${{ matrix.target_dir }}
          level: "waring"
          tflint_init: "true"
          reporter: github-pr-review
          fail_on_error: "true"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}

      - name: Terraform plan
        id: terraform_plan
        working-directory: ${{ matrix.target_dir }}
        continue-on-error: true
        run: |
          terraform plan \
            -input=false \
            -no-color \
            #-var 'db_password=${{ secrets.DB_PASSWORD }}' \
            #-var 'cloudflare_account_id=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}' \
            #-var 'cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}' \
            #-var 'user_api_session_secret=${{ secrets.USER_API_SESSION_SECRET }}' \
            #-detailed-exitcode
